#+TITLE: About me
#+AUTHOR: Yoshitaka TAKEUCHI
#+FILETAGS: :dialy:
#+DESCRIPTION: ブログを作りました。自己紹介の記事です。shellscriptで動くこのブログはできるだけ高い移植性を目指し、POSIXで定義されているコマンドとオプションを使い動いています。

#+OPTIONS: :html-container section
#+OPTIONS: num:nil
#+OPTIONS: ^:{}

* ブログをつくりました。
こんにちは。

このブログは僕が生産したことを残すためのブログです。
日々の生産を残すメディアがないと、自己紹介や就職、転職のときの話題提供ができなくなってしまうケースが多いなと感じて作りました。
  
プログラミングははじめて7年目くらいの初心者なので、記事の内容に間違いをみつけたら、どしどし指摘してください。。
そのうち、コメントとかの機能もつける予定。。。。

** なんで外部のホスティングサービスじゃだめなのか
*** 自分で管理することでの技術向上
どこの人がいつ言っていたのか忘れましたが、運用せずに研究はできないって言葉を大切にしています。
インターネットの規格は実際に利用されるなかで柔軟に変化していくものであり、実際に運用しなければ気づかないことが多くあると考え自分で管理することにしました。

*** リクエストログでのアクセス解析
多くのWebサイトはGoogle Analyticsなどのトラッカーを利用しています。
このようなサービスを利用し、ユーザに必要とされている情報を解析、提供することはユーザや提供者相互にメリットがあることです。
が、Googleなどの大企業のサービスを熟考なく導入することは大企業による寡占を進めます。

たとえば、iHerbというサプリメントの通販サイトを閲覧した直後に、Web広告が表示されるサイトを用いてプレゼンテーションを行なうと、
Web広告が殆どiHerbのサプリメントの広告になってしまい聴講者は集中できないばかりか発表者に関するセンシティブな情報が知られてしまうかもしれません。
(GoogleやiHerbが悪いサイトというわけではありません。)

たしかに、必要な人に必要な情報を表示することはメリットしかないことですが、Webサイトの閲覧履歴という思想や興味など重度の個人情報を数少ない企業が握ることは危険なことだと思います。
数少ない企業が突然evilになるかもしれないし、企業が籍を持つ国が情報統制を敷くためにあらゆる手段で世界中の人の思想を収集する法律を作り、企業が握った個人情報を接収するかもしれません。

企業がサービスを行なうサイトは開発工数や使いやすさで利益のために大企業のサービスを導入することも良いとおもいます。

しかし、これは折角自分で運用するブログなので、リクエストログだけでどれくらいのアクセス解析ができるのか試そうという意図もあり、ブログを自営することにしました。

*** 広告運用
広告運用のプラットフォームを自作してみようっかなとおもってます。
後々。。。。

* 自分について
[[http://cv.baud.jp][履歴書？]]

詳しいことや採用の方は↑のリンク先をチェックしてください。
学生身分ですが、お仕事をさがしています。

国立東京高専を卒業して放送大学で大学院にいくための単位をあつめようとしています。
大学院ではインターネットの非中央集権的なアーキテクチャを生かした研究をしたいです。(まだ未熟なので詳しくは直接聞いてほしい~)

足の靭帯の張力を測ったりする研究なんかもしてます。


インターネットにコンピュータを繋ぐことで世界と繋がれることに感動してからネットワークが趣味になりました。(ネットワークビジネスのことではない。)

インターネットの素晴らしいとおもったところについては話すと長くなるので聞きたい人は会ったときに覚悟して聞いてください。
L2~L4らへんが好きです。

海外旅行が好きで良くいきます。
おすすめはバルセロナ。

車も好き。あとはお酒

* LICENSE
このサイトにあるコードとか文章は特記ない場合CC0/Beerwareです。
著作権などは主張しないので煮るなり焼くなりすきにしてください。

この文章を読むすべての人は僕にビールをおごることができます。

役にたった場合は教えてくれると非常によろこびます。

* POSIX-shell縛りのスクリプトでCMSを作ってみた。
最後にこのブログの動いてるシステムの簡単な説明です。
詳しくはまたこんど書きます。

このブログシステム(CMS?)は、POSIXで定義されているコマンドとそのオプションを使ってつくられています。
POSIXで定義されているコマンドとそのオプションだけで作ることで高い移植性と環境構築が簡単なところに魅力を感じて言語を選択しました。

リポジトリは[[https://github.com/yosatak/weblog][ここ]]です。

** 実行環境
:PROPERTIES:
:ID: enviroment
:END:

blog.baud.jpは自宅マンションでうごくFreeBSD on RaspberryPi2でホスティングされています。(2019/3/12現在)
httpサーバにはOpenBSDhttpdを使っています。

システム自体はシェルスクリプトなのでPOSIXに準拠したコンピュータとCGIが使える適当なhttpサーバがあればわりとどの環境でもうごくはず。

OpenBSD httpdを利用しているのは僕が普段のメインマシンがOpenBSDでそれに元々はいっていたからでFreeBSDを使っているのはraspberry piに挿さっていたSDカードに焼かれていたのがFreeBSDだからで深い理由はありません。

もし、同じCMSを使いたい人は好きなOSに好きなHTTPサーバを入れてつかってみてください。

このシステムに関しての説明は後日します。
