#+TITLE: 猫でも出来るICTSC敢闘賞
#+AUTHOR: Yoshitaka TAKEUCHI
#+FILETAGS: :dialy:
#+DESCRIPTION: ICTSCで3位になりました。大会としても強い人が増えることは良いとおもうので、とりあえず3位になるためにした事を纏めます。ネットワーク問、OS問からアプリケーションまで多岐に渡る問題で点数をとるためには技術力も必要ですが、戦略も得点への多きな力になるはずです。。。

#+OPTIONS: :html-container section
#+OPTIONS: num:nil
#+OPTIONS: ^:{}

* ICTSCで3位になりました。
プログラマの間では猫はC,C++,C#を始めとして色々な言語やネットワークやWindowsに関する教養がわかることが知られています。
高専に入学したときにこれらのスキルを持つ人は数人しかおらず、先日高専を卒業した僕はやっと猫に追い付けました。

そんな猫になってしまった僕は高専を卒業する2週間くらい前にICTSC2019で3位という猫らしい結果を残したので戦略などを共有します。
八王子市椚田町の最高学府東京高専のチーム名/dev/pts は猫よりも高い技術力をもつ1位や2位の慶應と東工大のチームには叶いませんでした。

懇親会で決勝出場の皆様とはなせることを楽しみにしています。

ちなみに、僕は犬派でなんなら猫はあんまり好きではない。

* ICTSCに出るまで
僕はICTSCの事を以前から知っており、3年生くらいから出よう出ようと思っていたのですが、毎年エントリーの締め切りを逃していました。

今年はtwitterで誰かがリツイートしていたICTSCの話題から検索してみると、丁度一週間後が締め切りだったので適当に仲がよかったメンバーを集め、エントリーしました。
メンバは特に忖度して選定した訳じゃなく、適当に。寮生の頃に相部屋だった友達とCPUオタクの後輩、二回留年したら同級生になった組み込み系が上手な友達に声かけました。

4人で1チームだと思ってたのですが、どうやら、5人で1チームだったようです。
第1回予選で他のチームが5人で出場してて、引率の先生かな？とか思ってたらどうやら違ったようです。

メンバーは自分の持たない知識を持った人を集めた方が良い気がしますが、CPUの命令や回路設計に関する問題はICTSCには出ないはずなので、多分近くにいる気が合う友達を集めるのが良いんだとおもいます。
ICTSCに出ようとする人の周りにいる気が合う友達は検索して問題解決する力がある人が多いはずですし。

ちなみに、中学時代吹奏楽部だった男は情報系の分野に詳しい確率70%,科学部78%,卓球部80%(たけうち調べ)

* 予選までにしたこと
ICTSCはネットワーク~OS~アプリケーションの障害解決力を試されます。

複数人でチームを組んで出場するので自分以外のメンバがそれぞれどんな技術を持っていたり興味があるのか知っていると、競技中にする会話のレベルが揃えやすく円滑なコミュニケーションの大きな支えになるでしょう。

僕はネットワークには興味こそありますが、完全に理解している訳ではないですし、コンテナの技術にはFreeBSDjailくらいしかまともに触ったことはありません。Dockerなんかは業務でたまに使うくらいで人に教えられるスキルはありません。

とりあえず、メンバ全員がICTSCの問題の出方、出題分野に関する教養を研究することが大事じゃないかとおもって過去問から1題づつ環境を再現して持ち寄り、それを他のメンバが回答する勉強会を開くことにしました。
過去問は回答方法こそ解説されているものの、イメージが公開されている訳でもないので問題を再現する環境を作ることは結構な力になります。
普段読み飛ばすconfigとかを読んで、勉強会の後に実はこんな機能があるみたいのを発表するのがポイントです。

2週間に1回勉強会を開催することで、問題再現や教養の取得に2週間、勉強会で他人が作った問題を3問解くみたいなペースは結構ハードで、結局3回くらいしかやりませんでしたが、力にはなりましたし、なによりもチームメンバが御互いのスキルを確認しあえるのが良かったです。

* 予選(1回目)
ICTSCには予選が2回あります。

1回目の予選はシード枠争いですが、足切りはないので、初出場の僕らはとりあえず、問題に慣れることを目的に集まって参加しました。
結果は1130点で12位でした
本戦出場圏内の10位まで22点差でしたが、勉強会の成果でしょうか？？？？？？

それぞれが集中して問題を解いているなかで適切なアドバイスを共有するのは中々大変です。
30分詰まっている問題が別のメンバーには3秒で答えられるかもしれません。
質問するときの粒度が大きすぎると質問される側が逆質問する頻度が増え、小さすぎると、何の話をしているのか判らなかったり、詰りどころが違うとアドバイス出来なかったりします。

ただ、業務でビジネス側と要件定義をする訳ではないので、コミュニケーションについての勉強をするよりかは、チームメンバのスキルを理解することが大事なのかなと思いました。

* 予選(2回目)
2回目の予選ですが、僕はヨーロッパにいて、しかも夜寝てしまったので寝坊して参加は最後の30分くらいだけでした。

残念

最後1問くらい解けましたが、日本で集まって解いていたメンバーが何をしていたのかはよく判りません。
埼玉に集合していたらしいです。

結果は13位でした。

あーあ

* 新人枠
東京高専は過去にICTSCに出場したことがないようで、新人用の枠で本戦出場になりました。

* 本戦
コロナウイルスによる肺炎が流行していて、リモート開催になってしまいました。

いままで、予選はできるだけメンバが集合して参加するようにしていたのですが、ICTSCは濃厚接触なので全員が自宅からリモートで参加することにしました。
いままでオフラインだったので詰ったところをボソボソ喋るとだれかしら反応してくれたのですが、電話だとそういう訳にもいきません。

(ex. Aさん<("ｱｱｯ ubuntｯ ﾈｯﾄworkﾃﾞｪ") Bさん<("netplaﾝﾝｯ") みたいな)

また、オフラインでも問題の回答を諦めて他のメンバに任せたいときの引き継ぎが結構課題感ありました。

そこで、普段コミュニケーションに使っていたdiscordに問題ごとにチャンネルを立ててした作業をメモしていくことにしました。

これが結構良くて円滑な回答に一役買ったとおもいます。

詰ってるときは大体他人の目でみると違うところに障害があったりするので視野の広さ大事。

僕たちのチームのスキルレベルだと、全員がフルスタックに動く必要が少なからずあります。
検索して解決していくためには初めてみるような環境を


s/メンバー/メンバ/g
